# Feeds to pull from. Must be in xml format and have "title" and "description" fields set.
feed_lists:
    - https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml
    - http://seclists.org/rss/bugtraq.rss

# Settings for slack
slack_username: "CVEStack"
slack_author: "CVEStack"
slack_webhook: "https://hooks.slack.com/services/XXXXXX/XXXXXXXXXXXXXXXXX"
slack_emoji_icon: ":lock:"

# Settings for syslog
syslog_address: '/dev/log'

# Posts every 5 minutes by default
post_interval: 5

# Defines if dependencies are ignored, vs included
dependencies_are_ignored: false

# Locations to push data
outputs:
    - syslog
    - slack
# The file to pull patterns from
pattern_file: '.dependencies.txt'

# Should we strip spaces? (may increase false positives)
strip_spaces: false